from typing import List
from unittest import TestCase

class JsonMinifyTestCase(TestCase):
    tests: List[List[str]]
    def template(self, index: int) -> None: ...
    def test_1(self) -> None: ...
    def test_2(self) -> None: ...
    def test_3(self) -> None: ...
    def test_4(self) -> None: ...
